### ISSUE TITLE
Launch Ilmopedia Kids Website

### ISSUE THREAD

**Issue by ZI-Youtuber** [IlmopediaKids/website#4]

**Comment by e-coders** [comment]
Hi there. I can help you too. Make me a contributor to the org as a manager. I will help, enable github pages, and do a lot more things. I didn't do any not-legal things.

**Comment by e-coders** [comment]
Thanks!

**Comment by e-coders** [comment]
Currently, I'm a little busy so can't work for it. But I will do it in few days - weeks.
